# =============================================================================
# MASTER DOCKER COMPOSE - DATA PLATFORM 1.3
# Environment-Aware Orchestration - WSL Optimized
# Usage: docker-compose --env-file .env.development up -d
# =============================================================================

name: ${COMPOSE_PROJECT_NAME:-data-project-13}

# Include all service compositions
include:
  - 6-infrastructure/docker/5-postgresql/docker-compose.yaml
  - 6-infrastructure/docker/1-kafka/docker-compose.yaml
  - 6-infrastructure/docker/2-spark/docker-compose.yaml
  - 6-infrastructure/docker/4-mlflow/docker-compose.yaml
  - 6-infrastructure/docker/3-airflow/docker-compose.yaml

# =============================================================================
# DYNAMIC NETWORK - ENVIRONMENT AWARE
# =============================================================================
networks:
  data-platform:
    name: ${NETWORK_NAME}
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET}
          gateway: ${NETWORK_GATEWAY}

# =============================================================================
# WSL-OPTIMIZED VOLUMES
# =============================================================================
volumes:
  # Essential bind mounts only
  shared-configs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/6-infrastructure/docker/5-config    
      
  shared-logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/logs                                
    
  # Docker managed - Better WSL performance
  shared-workspace:
    driver: local
    
  shared-workflows:
    driver: local
    
  shared-models:
    driver: local
    
  shared-data-processed:
    driver: local                                       
    
  spark-data:
    driver: local

  # Database volumes - Her environment için ayrı
  postgres-data:
    driver: local
    
  kafka1-data:
    driver: local
    
  kafka2-data:
    driver: local
    
  kafka3-data:
    driver: local
    
  airflow-postgres-data:
    driver: local
    
  mlflow-postgres-data:
    driver: local
    
  mlflow-minio-data:
    driver: local
